EMAIL_USER = "dtc@behrmanngroup.com"
EMAIL_PASSWORD = "$igmaAlpha1996"
OPENAI_API_KEY = "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"
